
* Física II

** Mecânica dos Fluidos

*** Pressão Hidrostática

**** Conceitos iniciais

Relembre os conceitos de [[file:area.org][Área]] ,  [[file:volume.org][volume]] e  [[file:densidade][densidade]] .

**** Conceito de pressão

É a força distribuida pela àrea sob a qual está aplicada:

\[ p = \frac{F}{A} \]

Explicação mais detalhada sobre [[file:conceito-de-pressao.org][conceito de pressão]] 


**** Pressão em um líquido

A pressão hidrostática é causada pelo peso de um fluido em eterminado
 ponto do fluido. Por exemplo, a pressão que você sente ao mergulhar
 em um lago. Quanto maior a profundidade, maior a
 pressão sob sua cabeça.

Essa pressão depende da densidade do fluido \( d\) , da aceleração da
gravidade \(g = 10 m/s^2\)  e da profundidade \(h\) onde se quer saber a
pressão \( p\) .


#+CAPTION: A pressão em um fluido se deve ao peso desse fluido, e depende da profundida.
#+ATTR_HTML: :width 400 :style text-align:center; display:block; margin:auto;
[[https://upload.wikimedia.org/wikipedia/commons/e/e7/Hydrostatic-pressure.svg]]
 
 
Para calcular essa pressão, basta considerar um certo volume de fluido
e dividir pela área desse volume. Por exemplo, seguindo os seguintes passos:

1. Peso de um volume fluido:
   \[F_P = m\, g\]
2. Peso de um volume, em termos da densidade e do volume, considerando
  a massa \(m=d\,V\):
   \[F_P = d\,\,V\,g\]
3. Peso do volume considerando área da base vezes altura \( V = A\,h\):
   \[p = \frac{F_P}{A}=\frac{d\,A\,h\,g\,}{A}\]
Dessa forma, obtemos uma expressão matemática que relaciona a pressão, com a densidade do fluido e a profundidade onde se quer calcular:

\[ 
p = d g h
\]























**** Pressão atmosférica

Apressão atmosférica é um tipo de pressão hidrostática, porém,
considerando que estamos envolvidos por um fluido que são os diversos
gases que compõe a atmosfera. A pressão atmosférica é causada pelo
peso da camada de atmosfera sob nossas cabeças. Assim, ela diminui
conforme a altitude aumenta.

Poderíamos utilizar a equação acima para calcular, também, a pressão
atmosférica. Porém, nesse caso, temos uma complicação, pois a
densidade não é constante (os gases ficam rarefeitos com a altitude, e
assim, a a densidade reduz).

Uma unidade de medida utilizada como padrão para comparação com a
pressão atmosférica é o \(atm\) que é, por definição, a pressão
atmosférica a nível do mar. Sua relação com a unidade pascal é:

\begin{equation}
1,000 \, atm = 101,3\, kPa
\end{equation}


[[file:quest-fisca2-1.org][Questões de revisão: Fluidos]]

*** Prensa Hidráulica

Como conseguimos levantar um carro com o pé utilizando um [[https://pt.wikipedia.org/wiki/Macaco_(ferramenta)][Macaco]]
Hidrálico ?

vamos analisar um exemplo mais simplificado de uma prensa hidráulica.

#+CAPTION: Ao aplicarmos uma força \(F_1\) no lado esquerdo dessa prensa hidráulica, resultará em uma força maior \(F_2\) no lado direito.
#+ATTR_HTML: :width 512 :style text-align:center; display:block; margin:auto;
[[https://upload.wikimedia.org/wikipedia/commons/9/99/Working_principle_of_a_hydraulic_jack.svg]]


A força e àrea (do pistão móvel) em cada lado, são inversamente proporcionais, em uma prensa hidráulica.

A explicação pode ser dada pelo Princípio de Pascal:

#+BEGIN_QUOTE
A pressão aplicada em um fluido em equilíbrio estático se distruibui
igualmente para todas as partes desse fluido.
#+END_QUOTE

Assim:

\[
 p_1 = p_2
\]

 
\[ \frac{F_1}{A_1} = \frac{F_2}{A_2} \]

*** Empuxo



Como um objeto pode ficar submerso em um fluido, um bloco de madeira
flutuando em água, por exemplo, se a força peso o empurra para baixo?

O empuxo é essa força que equilibra a força da gravidade quando o
objeto está submerso. E ela existe devido a diferença de pressão
hidrostática entre as superfícies do objeto submerso.


#+CAPTION: Força de Empuxo \(F_A\) e Força peso \(F_E\)
#+ATTR_HTML: :width 512 :style text-align:center; display:block; margin:auto;
[[https://upload.wikimedia.org/wikipedia/commons/1/10/Floating-and-sinking-2.svg]]


Princípio de Arquimedes para calcular o Empuxo:

 #+begin_quote
Um corpo imerso sofre a ação de uma força de empuxo dirigida para cima
e igual ao peso do fluido que ele desloca.
#+end_quote

#+CAPTION: Pelo princípio de Arquimedes, o objeto sofre uma força de empuxo igual ao peso do fluido deslocado.
#+ATTR_HTML: :width 512 :style text-align:center; display:block; margin:auto;
https://upload.wikimedia.org/wikipedia/commons/7/72/Archimedes-principle.svg


#+CAPTION: Um exemplo interessante é um barco flutuando em um rio: O peso do barco na figura (a) é sustentada pela força de empuxo representada na figura (b).
#+ATTR_HTML: :width 650 :style text-align:center; display:block; margin:auto;
https://upload.wikimedia.org/wikipedia/commons/2/26/Center_of_buoyancy.svg



*** Pressão Hidrodinâmica


*** Aerodinâmica

** Termodinâmica

*** Conceito de temperatura

*** Escalas termométricas

*** Dilatação Térmica

*** Conceito de calor

*** Calor específico

*** Calor latente

*** Transferência de calor

**** Condução

**** Convecção

**** Radiação

*** A primeira Lei da Termodinâmica

