
* Questão 1 – Velocidade do som

Sabendo que a velocidade de uma onda é dada por \( v = \lambda \cdot f \), em que:
- \( v \) é a velocidade da onda (em m/s),
- \( \lambda \) é o comprimento de onda (em metros),
- \( f \) é a frequência da onda (em Hz),

Considere que a frequência de 440 Hz de som está associada a um comprimento de onda de 0,600 m.  
Qual é a velocidade de propagação do som nesse caso?

**Alternativas:**
a) 240 m/s  
b) 264 m/s  
c) 330 m/s  
d) 360 m/s  




* Questão 3 – Som embaixo d'água

O som se propaga mais rapidamente na água do que no ar. Suponha que uma onda sonora se propague na água com comprimento de onda igual a 1,5 m e frequência de 1.000 Hz.  
Qual é a velocidade do som na água, nessa situação?

**Alternativas:**
a) 1.000 m/s  
b) 1.300 m/s  
c) 1.500 m/s  
d) 1.700 m/s  

* Questão 4 – Luz visível

A cor verde da luz visível está associada a um comprimento de onda de aproximadamente \( 5{,}5 \times 10^{-7} \) m.  
Qual a frequência dessa onda, considerando a velocidade da luz no vácuo igual a \( 3{,}0 \times 10^8 \, \text{m/s} \)?

**Alternativas:**
a) \( 5{,}5 \times 10^{14} \, \text{Hz} \)  
b) \( 4{,}5 \times 10^{14} \, \text{Hz} \)  
c) \( 6{,}0 \times 10^{14} \, \text{Hz} \)  
d) \( 3{,}0 \times 10^{13} \, \text{Hz} \)


* Questão 5 – Micro-ondas

Um forno de micro-ondas utiliza ondas eletromagnéticas com frequência típica de \( 2{,}45 \times 10^9 \, \text{Hz} \).  
Qual é o comprimento de onda correspondente, considerando a velocidade da luz \( 3{,}0 \times 10^8 \, \text{m/s} \)?

**Alternativas:**
a) 0,12 m  
b) 0,20 m  
c) 0,45 m  
d) 1,20 m  




* Questões sobre dB
** Questão 1
Qual o nível de intensidade sonora considerado confortável para uma conversa comum?

a) 10 dB  
b) 30 dB  
c) 60 dB  
d) 90 dB  

** Questão 2
Um som de 90 dB é quantas vezes mais intenso que um de 60 dB?

a) 2 vezes  
b) 10 vezes  
c) 100 vezes  
d) 1000 vezes  

** Questão 3
Qual destes sons está mais próximo do limite da dor?

a) 30 dB  
b) 60 dB  
c) 90 dB  
d) 120 dB  

** Questão 4
Se um som tem 0 dB, o que isso significa?

a) Não há som nenhum.  
b) É o som mais fraco que podemos ouvir.  
c) É o som mais forte possível.  
d) Significa silêncio absoluto.


[[https://docs.google.com/forms/d/1gB35mLsxaBF7gVevDkUEK8YX-DPnbuFY9XuqJY8fH1Q/edit][questões no google sheet]]

[[https://docs.google.com/forms/d/13jq9r8dyksMqAeB1XzcKCRbx5WSdtQMETdxzrmGS9lU/edit][Questões no googe sheet 2]]



Atividades para entrega até quarta-feira - 23/07

* Atividade de revisão ondas - 1

https://forms.gle/SSvwxpatDiFjgmab7

* Atividade de revisão ondas - 2

https://forms.gle/Cz584GDUuu6DUaR76




