#+options: toc:2
** Sugestões sobre como estudar


*** Métodos

É importante se atentar para a como estamos estudando e aprendendo, de
modo a tornar o estudo mais eficiente. Abaixo estão lincados alguns
artigos e vídeos sobre algumas técnicas simples para tornar o estudo mais eficiente.

- **Método Feynman**

Baseia-se no fato de que ensinar é uma das melhores formas de
aprender. Além disso pode ser considerada uma técnica de aprendizagem ativa.

🌐 [[https://conexao.pucminas.br/blog/dicas/tecnica-feynman/#:~:text=A%20T%C3%A9cnica%20Feynman%20%C3%A9%20um,estivesse%20conversando%20com%20uma%20crian%C3%A7a.][Método Feynman de estudo - Blog PUC Minas]] 

🎥 [[https://youtu.be/TVHUs67kwRk][Como Aprender TUDO Que Quiser: Técnica Feynman (5 Passos) - Canal:
Eureka!]]

- **Repetição Espaçada**

Baseada no ideia de Curva do Esquecimento.
Observação: A Curva do Esquecimento não é exata, mas serve como uma
ideia, ou uma média, de como memorizamos (ou não)um conteúdo, em função
do seu uso ou revisão algo do tempo.

🌐 [[https://blog.duolingo.com/pt/repeticao-espacada-no-aprendizado/][Repetição espaçada no aprendizado - Blog Duolingo]]

🎥 [[https://youtu.be/XG0CAM_VYdE][3 Formas de Aplicar a Prática Espaçada nos Estudos  - Susane Ribeiro]] 


- **Técnica Pomodoro**

Nosso cérebro tem um limite de tempo de concentração e precisa de
pequenos intervalos de descanso.

🌐 [[https://brasilescola.uol.com.br/dicas-de-estudo/tecnica-pomodoro-que-e-e-como-funciona.htm][Técnica Pomodoro - Brasil Escola Uol]]

🎥 [[https://youtu.be/YI9oxHGf6iE][Técnica Pomodoro - Dicas de estudo - Canal: Socratica Português]]



*** Princípios

Para além dos métodos de estudo, o que realmente é mais relevante é a
sua motivação para estudar e motivo por que você está estudando. Isso
pode mudar completamente não só a sua eficiencia no aprendizado, mas
também a sua relação com o conhecimento.

- **Busque motivação**

As motivações podem ser as mais variadas, e diferentes para cada
um. A melhor motivação é aquela que te faz gostar do processo. Sobre
esse assunto, sugiro os vídeos abaixo:

🎥 [[https://youtu.be/RQE_UHooRic][Feynman sobre o MELHOR método de ESTUDOS! - Canal: Universo Narrado]]

🎥 [[https://youtu.be/WYmsiB_Rk8c][Quem aprende rápido faz isso diferente - [Lúcia Helena
Galvão. Estoicismo Prático| Inteligência Plena]] 


*** Mais sobre o assunto

🌐 [[https://www.nexojornal.com.br/externo/2025/06/06/educacao-como-tirar-notas-boas-desempenho-academico][7 métodos para obter um desempenho acadêmico melhor - Nexo Jornal]]

[[https://youtu.be/Z24Td5mtKOs][Como aprender algo tão rápido que parece ilegal (com base em evidências) - Python Programmer
@gilesmcmullen]] 
