
** Sugestões sobre como estudar

É importante se atentar para a forma como estamos estudando e
aprendendo, de moda a tornar o estudo mais eficiente. Abaixo estão
lincados alguns artigos e vídeos simples sobre cada uma das sugestões
para tornar o estudo mais eficiente.

- **Método Feynman**

Baseia-se no fato de que ensinar é uma das melhores formas de
aprender. Além disso pode ser considerada uma técnica de aprendizagem ativa.

🌐 [[https://conexao.pucminas.br/blog/dicas/tecnica-feynman/#:~:text=A%20T%C3%A9cnica%20Feynman%20%C3%A9%20um,estivesse%20conversando%20com%20uma%20crian%C3%A7a.][Método Feynman de estudo - Blog PUC Minas]] 

🎥 [[https://youtu.be/TVHUs67kwRk][Como Aprender TUDO Que Quiser: Técnica Feynman (5 Passos) - Canal:
Eureka!]]

- **Repetição Espaçada**

Baseada no conceito da Curva do Esquecimento.

🌐 [[https://blog.duolingo.com/pt/repeticao-espacada-no-aprendizado/][Repetição espaçada no aprendizado - Blog Duolingo]]

🎥 [[https://youtu.be/XG0CAM_VYdE][3 Formas de Aplicar a Prática Espaçada nos Estudos  - Susane Ribeiro]] 


- **Técnica do Pomodoro**

Nosso cérebro tem um limite de tempo de concentração e precisa de
pequenos intervalos de descanso.

🌐 [[https://brasilescola.uol.com.br/dicas-de-estudo/tecnica-pomodoro-que-e-e-como-funciona.htm][Técnica Pomodoro - Brasil Escola Uol]]

🎥 https://youtu.be/YI9oxHGf6iE

- **Busque motivação**

As motivações podem ser as mais variadas, e diferentes para cada
um. Mas ela deve existir. Mais a melhor motivação é aquela que te faz
gostar do processo. Sobre isso, sugiro o vídeo abaixo:

[[https://youtu.be/RQE_UHooRic][Feynman sobre o MELHOR método de ESTUDOS! - Canal: Universo Narrado]]
